[project]
authors = ["Alistair Miles <alimanfoo@googlemail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "2024-11-16-llm-use-case"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"

[pypi-dependencies]
jupyterlab = ">=4.3.1, <5"
nbconvert = ">=7.16.4, <8"
nbformat = ">=5.10.4, <6"
ipykernel = ">=6.29.5, <7"
pixi-kernel = ">=0.5.1, <0.6"
malariagen-data = ">=13.5.0, <14"
