# Site settings
title: alimanfoo
email: alimanfoo@googlemail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://alimanfoo.github.io" # the base hostname & protocol for your site
twitter_username: alimanfoo
github_username:  alimanfoo

# Build settings
markdown: kramdown
exclude: ['*.sh', '_posts/data']
