[project]
authors = ["Alistair Miles <alimanfoo@googlemail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "2024-08-19-nb-test"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.11.*"
jupyterlab = ">=4.2.4,<5"
notebook = ">=7.2.1,<8"
nbconvert = ">=7.16.4,<8"
plotly = ">=5.23.0,<6"
pandas = ">=2.2.2,<3"
bokeh = ">=3.5.1,<4"
ipykernel = ">=6.29.5,<7"
