[project]
authors = ["Alistair Miles <alimanfoo@googlemail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "2024-10-18-faster-neighbour-joining"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"

[pypi-dependencies]
jupyterlab = ">=4.2.5, <5"
nbconvert = ">=7.16.4, <8"
plotly = ">=5.24.1, <6"
anjl = ">=1.1.3, <2"
