[project]
authors = ["Alistair Miles <alimanfoo@googlemail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "2024-08-16-diplotype-clustering"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.11.*"
jupyterlab = ">=4.2.4,<5"
notebook = ">=7.2.1,<8"

[pypi-dependencies]
malariagen-data = ">=12.0.0, <13"
